version: "3.5"

services:
  front:
    build: "../../part1/1.14 Environment/front/"
    container_name: front-end
    ports:
      - "5000:5000"
  back:
    build: "../../part1/1.14 Environment/back/"
    container_name: back-end
    ports:
      - "8080:8080"
